CREATE TABLE `flaskTutorial`.`2018_season_per_game` (
  `index` INT NOT NULL AUTO_INCREMENT,
  `player_id` INT NOT NULL,
  `season_id` VARCHAR(45) NOT NULL,
  `team_abbreviation` VARCHAR(45) NULL,
  `gp` INT NULL,
  `gs` INT NULL,
  `min` DECIMAL(4,2) NULL,
  `fgm` DECIMAL(4,2) NULL,
  `fga` DECIMAL(4,2) NULL,
  `fg_pct` DECIMAL(4,3) NULL,
  `ftm` DECIMAL(4,2) NULL,
  `fta` DECIMAL(4,2) NULL,
  `ft_pct` DECIMAL(4,3) NULL,
  `oreb` DECIMAL(4,2) NULL,
  `dreb` DECIMAL(4,2) NULL,
  `ast` DECIMAL(4,2) NULL,
  `stl` DECIMAL(4,2) NULL,
  `blk` DECIMAL(4,2) NULL,
  `tov` DECIMAL(4,2) NULL,
  `pf` DECIMAL(4,2) NULL,
  `pts` DECIMAL(4,2) NULL,
  PRIMARY KEY (`index`));
