CREATE TABLE `flaskTutorial`.`2015_season_per_game` (
  `index` INT NOT NULL AUTO_INCREMENT,
  `player_count` INT NULL,
  `league_id` INT NULL,
  `season_id` VARCHAR(45) NOT NULL,
  `player_id` INT NOT NULL,
  `pos` VARCHAR(10) NULL,
  `first_name` VARCHAR(30) NULL,
  `last_name` VARCHAR(30) NULL,
  `team_id` INT NULL,
  `team_abbreviation` VARCHAR(45) NULL,
  `yearsPro` INT NULL,
  `player_age` INT NULL,
  `gp` INT NULL,
  `gs` INT NULL,
  `min` DECIMAL(4,2) NULL,
  `fgm` DECIMAL(4,2) NULL,
  `fga` DECIMAL(4,2) NULL,
  `fg_pct` DECIMAL(4,3) NULL,
  `fg3m` DECIMAL(4,2) NULL,
  `fg3a` DECIMAL(4,2) NULL,
  `fg3_pct` DECIMAL(4,3) NULL,
  `ftm` DECIMAL(4,2) NULL,
  `fta` DECIMAL(4,2) NULL,
  `ft_pct` DECIMAL(4,3) NULL,
  `oreb` DECIMAL(4,2) NULL,
  `dreb` DECIMAL(4,2) NULL,
  `reb` DECIMAL(4,2) NULL,
  `ast` DECIMAL(4,2) NULL,
  `stl` DECIMAL(4,2) NULL,
  `blk` DECIMAL(4,2) NULL,
  `tov` DECIMAL(4,2) NULL,
  `pf` DECIMAL(4,2) NULL,
  `pts` DECIMAL(4,2) NULL,
  PRIMARY KEY (`index`));
