CREATE TABLE `flaskTutorial`.`players_game_log_2018` (
  `index` INT NOT NULL AUTO_INCREMENT,
  `player_count` INT NULL,
  `season_id` VARCHAR(45) NOT NULL,
  `player_id` INT NOT NULL,
  `game_id` INT NULL,
  `game_date` VARCHAR(20) NULL,
  `matchup` VARCHAR(30) NULL,
  `wl` VARCHAR(10) NULL,
  `min` DECIMAL(4,2) NULL,
  `fgm` DECIMAL(4,2) NULL,
  `fga` DECIMAL(4,2) NULL,
  `fg_pct` DECIMAL(4,3) NULL,
  `fg3m` DECIMAL(4,2) NULL,
  `fg3a` DECIMAL(4,2) NULL,
  `fg3_pct` DECIMAL(4,3) NULL,
  `ftm` DECIMAL(4,2) NULL,
  `fta` DECIMAL(4,2) NULL,
  `ft_pct` DECIMAL(4,3) NULL,
  `oreb` DECIMAL(4,2) NULL,
  `dreb` DECIMAL(4,2) NULL,
  `reb` DECIMAL(4,2) NULL,
  `ast` DECIMAL(4,2) NULL,
  `stl` DECIMAL(4,2) NULL,
  `blk` DECIMAL(4,2) NULL,
  `tov` DECIMAL(4,2) NULL,
  `pf` DECIMAL(4,2) NULL,
  `pts` DECIMAL(4,2) NULL,
  `plus_minus` INT NULL,
  PRIMARY KEY (`index`));
